const List<Map<String, dynamic>> users = [
  {
    'name': '박성일',
    'description': "열심히 하겠습니다!",
    'role': '팀장',
    'badges': ['개발', '운동', '헬스 케어'],
    'profileImage': 'image1.jpeg',
    'birth': '2002.05.15',
    'gender': '남성',
    'mbti': 'INTP',
    'position': '앱 개발',
    'location': '경남 통영',
    'interests': '개발, 운동, 독서',
    'skills': {
      'Java': 1.0,
      'Kotlin': 0.7,
      'Spring': 0.8,
    },
    'capabilities': {
      '창의성': 1.0,
      '적극성': 0.9,
      '리더십': 0.9,
      '끈기': 0.9,
      '협력': 0.9,
      '책임감': 0.9,
    }
  },
  {
    'name': '박해솔',
    'description': "잘 부탁드립니다.",
    'role': '팀원',
    'badges': ['게임', '그림', '잠자기'],
    'profileImage': 'image2.jpeg',
    'birth': '1995.01.21',
    'gender': '여성',
    'mbti': 'INFP',
    'position': '디자인',
    'specialty': '섬세한 그래픽 디자인',
    'location': '광주광역시',
    'interests': '디자인, 배리어 프리, 음악 감상',
    'skills': {
      'Photoshop': 0.9,
      'Clip Studio': 0.9,
      'Indesign': 0.9,
    },
    'capabilities': {
      '창의성': 1.0,
      '적극성': 0.8,
      '리더십': 0.9,
      '끈기': 0.7,
      '협력': 1.0,
      '책임감': 0.7,
    }
  },
  {
    'name': '이재언',
    'description': "나의 한줄 소개",
    'role': '팀원',
    'badges': ['UX 디자인', 'UI 디자인', '창업', '서비스 디자인'],
    'profileImage': 'image3.jpeg',
    'birth': '1999.12.22',
    'gender': '남성',
    'mbti': 'ESTP',
    'position': 'UX/UI 디자인',
    'specialty': '사용자 경험 설계',
    'location': '경상남도 김해시',
    'interests': '웹툰, 패션, 여행',
    'skills': {
      'Figma': 0.8,
      'Photoshop': 0.5,
      'illustrator': 0.4,
    },
    'capabilities': {
      '창의성': 0.5,
      '적극성': 0.7,
      '리더십': 0.8,
      '끈기': 1.0,
      '협력': 0.7,
      '책임감': 0.9,
    }
  },
  {
    'name': '정선교',
    'description': "덕업일치 개발자",
    'role': '팀원',
    'badges': ['인프라', '서버 개발', '러닝', '사이드 프로젝트'],
    'profileImage': 'image4.jpeg',
    'birth': '1996.04.05',
    'gender': '남성',
    'mbti': 'ISTP',
    'position': '백엔드 개발자',
    'location': '신림동',
    'interests': '러닝, 헬스, 데이터 분석',
    'skills': {
      'TypeScript': 1.0,
      'Nest.js': 1.0,
      'MySQL': 0.8,
      'Kubernetes': 0.5,
      'ElasticSearch': 0.4,
    },
    'capabilities': {
      '창의성': 0.9,
      '적극성': 0.7,
      '리더십': 0.6,
      '끈기': 0.9,
      '협력': 0.8,
      '책임감': 0.7,
    }
  },
  {
    'name': '오민수',
    'description': "변화는 있어도, 변함은 없다",
    'role': '팀원',
    'badges': ['개발', '예술', '헬스 케어', '시니어'],
    'profileImage': 'image5.jpeg',
    'birth': '1995.09.03',
    'gender': '남성',
    'mbti': 'ENTJ',
    'position': '프론트엔드 개발',
    'specialty': '종합예술',
    'location': '대구광역시',
    'interests': '과거, 현재, 미래',
    'skills': {
      'MATLAB': 0.7,
      'Adobe XD': 0.6,
      'Google': 0.9,
    },
    'capabilities': {
      '창의성': 0.8,
      '적극성': 0.9,
      '리더십': 0.7,
      '끈기': 0.9,
      '협력': 0.7,
      '책임감': 0.8,
    }
  },
];
